### ISSUE TITLE
请问FaceNet网络结构推理过程中的MaxPool和ReLU是怎么处理的呢？

### ISSUE THREAD

**Issue by fantasysee** [DevilLost/Secure-Face-Recognition-System-based-on-Fully-Homomorphic-Encryption#4]
DevilLost你好！

FaceNet的深度神经网络结构中存在MaxPool和ReLU单元，请问您是怎么处理的呢？据我所知，同态加密运算目前只支持乘法和加法，不做线性化近似或替代是无法表示MaxPool和ReLU单元的。

另外，密文之间应该也无法进行比较，所以FaceNet是对两张人脸输出两个embedding特征向量，然后传回device端解密后判断两人脸是否一致，请问是这个思路吗？

以上两个问题恳请赐教。

祝好！

**Comment by DevilLost** [comment]
您好，首先非常感谢您关注我们的这个作品。
关于您提到的两个问题，我先做一个背景解释，我是一名计算机专业的本科在校生，从大二开始跟着我的导师做项目，方向是全同态加密和区块链。大三之后我开始学习人工智能方面的内容，我的导师就给了我新的学习方向，也就是将全同态加密与人工智能相结合。本项目只是我们研究团队做的第一个尝试，核心方法论源自一篇论文。
接下来我来回答您的两个问题：
第一个问题，建议您可以再仔细阅读一下本项目的README，我们的方法是先使用FaceNet模型获取到512维的人脸特征向量，然后再使用公钥加密特征向量并上传至数据库，也就是说在FaceNet模型调用阶段是明文状态而不是密文状态。
第二个问题，密文之间是可以进行比较的(看具体算法)，但是需要进行数学近似。FaceNet的特征向量比较算法用的是欧氏空间向量距离算法，同态加密无法处理根号计算，那么我们采用的方法是数学近似(建议您阅读相关论文的方法论，几乎都是用数学近似的方法来处理)。在本项目中，两个512维的密文人脸特征向量，我们采用的是信息论中的汉明距离算法来进行欧氏空间向量距离计算的一个数学近似，而汉明距离算法就可以被同态加密所接受。但是同样的也造成了数据误差，在FaceNet中特征向量距离阈值为1.0，而我们通过密文计算后得到的阈值大约为0.752。在服务器中通过密文特征向量比较后自然会得到一个密文状态下的距离值，服务器将密文距离回传至客户端，用户再使用私钥进行解密来得知比对验证是否通过。
PS：这里补充一点，就是您在第一个问题中提到的，同态加密如何对MaxPool和ReLU进行处理，就是我上面的回答中说的，使用数学近似方法。还有就是本项目只是我们研究团队的第一次尝试，密码学和人工智能两个技术的交叉度并不高，是在19年5月份完成的，在之后我们团队又完成了密文逻辑回归模型训练和密文深度学习模型训练，也就是您提问中所涉及的密文下的模型训练方法，如果您感兴趣可以跟我的导师交流，相信您一定会有更大的收获，我导师的联系方式：陈智罡博士：zhig.chen@foxmail.com


最后，再次对您的关注和致信表示感谢。
祝好！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chao Fang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上11:13
收件人:&nbsp;"DevilLost/Secure-Face-Recognition-System-based-on-Fully-Homomorphic-Encryption"<Secure-Face-Recognition-System-based-on-Fully-Homomorphic-Encryption@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[DevilLost/Secure-Face-Recognition-System-based-on-Fully-Homomorphic-Encryption] 请问FaceNet网络结构推理过程中的MaxPool和ReLU是怎么处理的呢？ (#4)





 
DevilLost你好！
 
FaceNet的深度神经网络结构中存在MaxPool和ReLU单元，请问您是怎么处理的呢？据我所知，同态加密运算目前只支持乘法和加法，不做线性化近似或替代是无法表示MaxPool和ReLU单元的。
 
另外，密文之间应该也无法进行比较，所以FaceNet是对两张人脸输出两个embedding特征向量，然后传回device端解密后判断两人脸是否一致，请问是这个思路吗？
 
以上两个问题恳请赐教。
 
祝好！

**Comment by DevilLost** [comment]
上文中MsxPool为MaxPool，输入有误，非常抱歉

**Comment by fantasysee** [comment]
非常感谢您的热心回复！受教了！！！再次表达感谢！！！
